### PR TITLE
Assignment 1 of SE part (Ahmad Saeed Khan)

### PR DESCRIPTION
**Pull request by askhanatgithub**

### CODE REVIEW

**Comment by robertfeldt** [comment]
Thanks Ahmad. This is a good start but please try to expand a little bit about the connections to your project. What kind of models and code do you plan to develop in your project and what kind of more specific features of static analysis tools do you think can be useful, given your use case? You can also consider other static analysis tools as mentioned in my slides, to give you ideas on possible, future features. Say something very short about your research/project so reader can understand where you are coming from in relation to static analysis. Thanks!

**Comment by robertfeldt** [comment]
Thanks, looks good.

**Comment by askhanatgithub** [comment]
Thank you so much for guidance and prompt feedback.

**Comment by robertfeldt** [comment]
No worries. Now merged your PR. Assignment 1 is done for you. :)

**Pull request merged**
